name: llm_client
description: A simple LLM client, providing ChatGPT-like functionality in a function call.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1

dependencies: 
  http: ^0.13.5
